services:
  app:
    build:
      context: .
      dockerfile: src/deployment/docker/Dockerfile
    container_name: ml_app
    environment:
      - MODEL_PATH=/src/models/saved_model  # Specify the model path for loading in the container
      - DATA_PATH=/data/processed           # Path to processed data
    volumes:
      - ./data:/data                        # Mount local data folder to container
      - ./src:/src                          # Mount src code to container for live updates
    ports:
      - "5000:5000"                         # Expose API service port (adjust as needed for FastAPI/Flask)
    depends_on:
      - mlflow-db
    command: ["python", "/src/deployment/api.py"]  # Start the FastAPI/Flask API server

  mlflow:
    image: mlflow/mlflow:latest
    container_name: mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow_user:mlflow_pass@mlflow-db/mlflow_db
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlflow:/mlflow                       # Mount local folder for MLflow artifacts
    ports:
      - "5001:5000"                            # Expose MLflow server on port 5001
    depends_on:
      - mlflow-db

  mlflow-db:
    image: postgres:13
    container_name: mlflow-db
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_pass
      POSTGRES_DB: mlflow_db
    volumes:
      - mlflow-db-data:/var/lib/postgresql/data

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebooks:/home/jovyan/notebooks      # Mount local notebooks folder to container
      - ./data:/data                            # Access data folder for EDA
      - ./src:/src                              # Access source code if needed in notebooks
    ports:
      - "8888:8888"                             # Expose Jupyter notebook on port 8888
    command: start-notebook.sh --NotebookApp.token=''

volumes:
  mlflow-db-data:
    driver: local
